version: '3.9'

services:

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: '${APP_NAME}-web'
    ports:
      - '${APP_PORT}:80'
      - '${APP_PORT_SSL}:443'
    working_dir: /var/www/html
    environment:
      - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@database:3306/${MYSQL_DB}'
      - TZ=Europe/Warsaw
    volumes:
      - ./:/var/www/html
      - ./docker/web/apache2/sites-available:/etc/apache2/sites-available
      - ./docker/web/apache2/ssl:/etc/apache2/ssl
      - ./docker/web/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    container_name: '${APP_NAME}-db'
    hostname: ${MYSQL_HOSTNAME}
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
      TZ: Europe/Warsaw
    volumes:
      - ./db/mariadb:/var/lib/mysql
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5

  pma:
    image: phpmyadmin/phpmyadmin:5
    container_name: '${APP_NAME}-phpmyadmin'
    ports:
      - '${APP_PMA_PORT}:80'
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./docker/phpmyadmin/config.php:/etc/phpmyadmin/config.user.inc.php