version: '3.9'

services:

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        - APP_PHP_VERSION=${APP_PHP_VERSION}
    container_name: ${APP_NAME}-web
    ports:
      - ${APP_PORT}:80
      - ${APP_PORT_SSL}:443
    working_dir: /var/www/html
    environment:
      - TZ=${APP_TZ}
    volumes:
      - ./:/var/www/html
      - ./docker/web/apache2/sites-available:/etc/apache2/sites-available
      - ./docker/web/apache2/ssl:/etc/apache2/ssl
      - ./docker/web/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    container_name: ${APP_NAME}-db
    hostname: ${MYSQL_HOSTNAME}
    restart: always
    ports:
      - ${APP_DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=${MYSQL_DB}
      - TZ=${APP_TZ}
    volumes:
      - ./db/mariadb:/var/lib/mysql
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-pma
    ports:
      - ${APP_PMA_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./docker/pma/config.php:/etc/phpmyadmin/config.user.inc.php